// Maps the game pad button codes to their names for debugging purposes.
global.gmcu_gamepad_buttons_mapping = {};
global.gmcu_gamepad_buttons_mapping[$ string(gp_face1)] = "gp_face1";       // Top button 1 (A on Xbox, cross on PS)
global.gmcu_gamepad_buttons_mapping[$ string(gp_face2)] = "gp_face2";       // Top button 2 (B on Xbox, circle on PS)
global.gmcu_gamepad_buttons_mapping[$ string(gp_face3)] = "gp_face3";       // Top button 3 (X on Xbox, square on PS)
global.gmcu_gamepad_buttons_mapping[$ string(gp_face4)] = "gp_face4";       // Top button 4 (Y on Xbox, triangle on PS)
global.gmcu_gamepad_buttons_mapping[$ string(gp_shoulderl)] = "gp_shoulderl"; // Left shoulder button
global.gmcu_gamepad_buttons_mapping[$ string(gp_shoulderlb)] = "gp_shoulderlb"; // Left shoulder trigger
global.gmcu_gamepad_buttons_mapping[$ string(gp_shoulderr)] = "gp_shoulderr"; // Right shoulder button
global.gmcu_gamepad_buttons_mapping[$ string(gp_shoulderrb)] = "gp_shoulderrb"; // Right shoulder trigger
global.gmcu_gamepad_buttons_mapping[$ string(gp_select)] = "gp_select";     // Select button (touchpad on PS)
global.gmcu_gamepad_buttons_mapping[$ string(gp_start)] = "gp_start";       // Start button (options on PS)
global.gmcu_gamepad_buttons_mapping[$ string(gp_stickl)] = "gp_stickl";     // Left stick pressed
global.gmcu_gamepad_buttons_mapping[$ string(gp_stickr)] = "gp_stickr";     // Right stick pressed
global.gmcu_gamepad_buttons_mapping[$ string(gp_padu)] = "gp_padu";         // D-pad up
global.gmcu_gamepad_buttons_mapping[$ string(gp_padd)] = "gp_padd";         // D-pad down
global.gmcu_gamepad_buttons_mapping[$ string(gp_padl)] = "gp_padl";         // D-pad left
global.gmcu_gamepad_buttons_mapping[$ string(gp_padr)] = "gp_padr";         // D-pad right
global.gmcu_gamepad_buttons_mapping[$ string(gp_home)] = "gp_home";         // Home button (logo button on Xbox/PS)
global.gmcu_gamepad_buttons_mapping[$ string(gp_touchpadbutton)] = "gp_touchpadbutton"; // Touchpad button on PS
global.gmcu_gamepad_buttons_mapping[$ string(gp_paddler)] = "gp_paddler";   // Upper paddle, right hand (e.g., Xbox Elite P1)
global.gmcu_gamepad_buttons_mapping[$ string(gp_paddlel)] = "gp_paddlel";   // Upper paddle, left hand (e.g., Xbox Elite P3)
global.gmcu_gamepad_buttons_mapping[$ string(gp_paddlerb)] = "gp_paddlerb"; // Lower paddle, right hand (e.g., Xbox Elite P2)
global.gmcu_gamepad_buttons_mapping[$ string(gp_paddlelb)] = "gp_paddlelb"; // Lower paddle, left hand (e.g., Xbox Elite P4)
global.gmcu_gamepad_buttons_mapping[$ string(gp_extra1)] = "gp_extra1";     // Extra button 1
global.gmcu_gamepad_buttons_mapping[$ string(gp_extra2)] = "gp_extra2";     // Extra button 2
global.gmcu_gamepad_buttons_mapping[$ string(gp_extra3)] = "gp_extra3";     // Extra button 3
global.gmcu_gamepad_buttons_mapping[$ string(gp_extra4)] = "gp_extra4";     // Extra button 4
global.gmcu_gamepad_buttons_mapping[$ string(gp_extra5)] = "gp_extra5";     // Extra button 5
global.gmcu_gamepad_buttons_mapping[$ string(gp_extra6)] = "gp_extra6";     // Extra button 6
